# Generated by Django 3.0.8 on 2020-07-26 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match', '0011_main_substitution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_pass', models.PositiveIntegerField(default=0)),
                ('long_pass', models.PositiveIntegerField(default=0)),
                ('danger_pass', models.PositiveIntegerField(default=0)),
                ('not_danger_pass', models.PositiveIntegerField(default=0)),
                ('cross', models.PositiveIntegerField(default=0)),
                ('flat', models.PositiveIntegerField(default=0)),
                ('foul_goal', models.PositiveIntegerField(default=0)),
                ('foul_try', models.PositiveIntegerField(default=0)),
                ('foul_none', models.PositiveIntegerField(default=0)),
                ('corner_goal', models.PositiveIntegerField(default=0)),
                ('corner_try', models.PositiveIntegerField(default=0)),
                ('corner_none', models.PositiveIntegerField(default=0)),
                ('tackl_ok', models.PositiveIntegerField(default=0)),
                ('tackl_none', models.PositiveIntegerField(default=0)),
                ('dribble_try', models.PositiveIntegerField(default=0)),
                ('dribble_none', models.PositiveIntegerField(default=0)),
                ('g_keeper_safe', models.PositiveIntegerField(default=0)),
                ('g_keeper_danger', models.PositiveIntegerField(default=0)),
                ('block_good', models.PositiveIntegerField(default=0)),
                ('block_bad', models.PositiveIntegerField(default=0)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_field', to='match.Main')),
            ],
        ),
    ]
