# Generated by Django 3.0.8 on 2020-07-27 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0011_main_substitution'),
        ('match_statics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_field', to='match.PlayerName'),
        ),
    ]
