# Generated by Django 3.0.8 on 2020-07-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_statics', '0002_auto_20200727_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='block_bad',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='block_good',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='corner_goal',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='corner_none',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='corner_try',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='cross',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='danger_pass',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='dribble_none',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='dribble_try',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='flat',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='foul_goal',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='foul_none',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='foul_try',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='g_keeper_danger',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='g_keeper_safe',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='not_danger_pass',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='tackl_none',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='tackl_ok',
        ),
    ]
