# Generated by Django 3.0.8 on 2020-07-29 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0011_main_substitution'),
        ('match_statics', '0003_auto_20200728_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='main',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='match.PlayerName'),
        ),
    ]
