# Generated by Django 3.0.8 on 2020-07-23 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20200723_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playername',
            name='match',
        ),
        migrations.RemoveField(
            model_name='playername',
            name='name_box',
        ),
        migrations.CreateModel(
            name='PlayerBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_name', to='match.Match')),
            ],
        ),
    ]
