# Generated by Django 3.0.8 on 2020-07-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20200723_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerbox',
            name='match',
        ),
        migrations.AddField(
            model_name='playerbox',
            name='name_box',
            field=models.CharField(choices=[], default=False, max_length=255),
            preserve_default=False,
        ),
    ]
