# Generated by Django 3.0.8 on 2020-07-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_auto_20200723_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerbox',
            name='players',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
