# Generated by Django 3.0.8 on 2020-07-23 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_playerbox_players'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerBox',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_slug',
        ),
    ]
