# Generated by Django 3.0.8 on 2020-07-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_auto_20200723_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.CharField(choices=[('Hossam Hassan', 'Hossam Hassan'), ('Wael Gomaa', 'Wael Gomaa'), ('Ibrahem Hassan', 'Ibrahem Hassan'), ('Barakat', 'Barakat'), ('Abou Treka', 'Abou Treka'), ('Ali Maalool', 'Ali Maalool'), ('Trezeget', 'Trezeget'), ('Shennawy', 'Shennawy')], default='Hossam Hassan', max_length=255)),
            ],
        ),
    ]
