# Generated by Django 3.0.8 on 2020-07-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_playerbase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerbase',
            name='box',
            field=models.CharField(max_length=255),
        ),
    ]
