# Generated by Django 3.0.8 on 2020-07-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_auto_20200724_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerBaseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
