# Generated by Django 3.0.8 on 2020-07-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_playerbasedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.CharField(max_length=255)),
            ],
        ),
    ]
