# Generated by Django 3.0.8 on 2020-07-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0010_playermain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=255)),
            ],
        ),
    ]
